### ISSUE TITLE
Bug trong phần "Thi sát hạch"

### ISSUE THREAD

**Issue by trungdinh98** [HugManh/INT3120-2020#9]
Khi chọn vào phần "Thi sát hạch", rồi chọn "Đề số 2" thì sẽ bị direct sang chức năng "Học lý thuyết", trong khi click các đề thi khác thì không. Mình không rõ đây có phải là bug hay là tính năng mà các bạn chưa hoàn thiện nữa nên để tạm là bug

**Comment by HugManh** [comment]
cái này nhóm mình chưa hoàn thiện, cái đề số 2 mình đăng để giao diện của "Học lý thuyết" nên ấn vào nó ra màn hình này
